sudo: required
services:
    - docker

before_install:
    - docker build -t michaeljkavanagh/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true michaeljkavanagh/docker-react npm run test